spring:
  application:
    name: consumer-api
  cloud:
    stream:
      bindings:
        iot-data:
          destination: iot-data
          group: output-group-1
          content-type: application/json
      kafka:
        binder:
          brokers:
            - localhost:9092
          consumer:
            configuration:
              key.deserializer: org.apache.kafka.common.serialization.LongDeserializer
              value.deserializer: org.springframework.kafka.support.serializer.JsonDeserializer