server:
  port: 8080
spring:
  devtools:
    livereload:
      enabled: true
  jmx:
    default-domain: workmotion
  main:
    allow-bean-definition-overriding: true
  jackson:
    default-property-inclusion: NON_NULL
    serialization.write_dates_as_timestamps: false
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: create

springdoc:
  swagger-ui.path: /openapi/swagger-ui.html
  swagger-ui.operationsSorter: method
  api-docs.path: /openapi/v3/api-docs
  packagesToScan: edu.prao.workmotion
  pathsToMatch: /**
api:
  common:
    version: 1.0.0
    title: WorkMotion Senior Challenge APIs

  responseCodes:
    ok.description: OK
    created.description: Created Successfully
    accepted.description: Updated Successfully
    badRequest.description: Bad Request, invalid format of the request
    notFound.description: Not found, the specified employee id does not exist

  employee:
    add_employee:
      description: Adds new employee to the system & returns saved employee, available actions
    get_employee_details:
      description: For the given EmployeeId, retrives employee info & available actions from the system
    update_employee_state:
      description:  For the given event, update Employee Status & returns updated employee, available actions